name: Nitro Anniversary Update

on:
  schedule:
    - cron: '45 20 * * *' # Wakes up 15 minutes early to bypass the GitHub queue
  workflow_dispatch: 

jobs:
  update-widget:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install axios dotenv

      - name: Run Update Script
        env:
          DISCORD_APP_ID: ${{ secrets.DISCORD_APP_ID }}
          DISCORD_USER_ID: ${{ secrets.DISCORD_USER_ID }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        run: node update-widget.mjs
